### PR TITLE
📜❌🙌 Added a .gitignore 

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by d4rpx1 — COMMENTED** [review]
It would be better to hide those files, not remove them, right?

**Review by d4rpx1 — APPROVED** [review]

**Review by d4rpx1 — CHANGES_REQUESTED** [review]
It would be better not to remove the files and only to hide them.

**Comment by ghost** [comment]
That's what .gitignore does. It ignores adding files recursively, like `git add .` will not try and add files that are exempt in the .gitignore. 
There are a few reasons why:
- You would use continuous integration, like Jenkins to compile and deploy your project
- The Jar files can lead to confusion when someone wants to use your plugin; you want users to use the most up to date version of your compiled plugin.
- It's unnecessary space and takes awhile to upload when you have a big project.
- It's clunky.

**Comment by d4rpx1** [comment]
> That's what .gitignore does. It ignores adding files recursively, like `git add .` will not try and add files that are exempt in the .gitignore.
> There are a few reasons why:
> 
> * You would use continuous integration, like Jenkins to compile and deploy your project
> * The Jar files can lead to confusion when someone wants to use your plugin; you want users to use the most up to date version of your compiled plugin.
> * It's unnecessary space and takes awhile to upload when you have a big project.
> * It's clunky.

Ohh, allright.

**Review by d4rpx1 — APPROVED** [review]

**Pull request merged**
